#!/bin/bash
# apply a patch release using https://github.com/mikaelbr/mversion

git branch | grep '* master' > /dev/null || (echo "Must be on master branch" ; exit 1) || exit 1
mversion patch -m 'Bumped to v%s' --tag 'v%s' || exit 2
git push origin --tags
