#!/bin/bash
# apply a patch release using https://github.com/mikaelbr/mversion

grunt test || exit 1
git branch | grep '* master' > /dev/null || (echo "Must be on master branch" ; exit 1) || exit 2
grunt build
git commit  -m 'build' build/module.js
mversion patch -m 'Bumped to v%s' --tag 'v%s' || exit 3
git push origin --tags
git push origin 
